// Generated by CoffeeScript 1.3.1
(function() {
  var CATMAP, onFeatureSelect, onFeatureUnselect;

  CATMAP = {};

  this.CATMAP = CATMAP;

  CATMAP.load_map = function(map_div_name) {
    var center, color, colors, controls, geoProj, ghyb, gmap, gsat, gterr, i, kmlDir, kmlFilename, kmlFilenames, kmlLayer, kmlLayers, kmlSelector, map, mercProj, osm, salina, styles, _i, _j, _len, _len1;
    geoProj = new OpenLayers.Projection("EPSG:4326");
    mercProj = new OpenLayers.Projection("EPSG:900913");
    controls = [
      new OpenLayers.Control.MousePosition({
        displayProjection: geoProj
      }), new OpenLayers.Control.OverviewMap, new OpenLayers.Control.KeyboardDefaults, new OpenLayers.Control.LayerSwitcher, new OpenLayers.Control.Navigation
    ];
    map = new OpenLayers.Map(map_div_name, {
      controls: controls
    });
    CATMAP.map = map;
    osm = new OpenLayers.Layer.OSM();
    map.addLayer(osm);
    gterr = new OpenLayers.Layer.Google("Google Terrain", {
      type: google.maps.MapTypeId.TERRAIN
    });
    gmap = new OpenLayers.Layer.Google("Google Streets", {
      numZoomLevels: 20
    });
    ghyb = new OpenLayers.Layer.Google("Google Hybrid", {
      type: google.maps.MapTypeId.HYBRID,
      numZoomLevels: 20
    });
    gsat = new OpenLayers.Layer.Google("Google Satellite", {
      type: google.maps.MapTypeId.SATELLITE,
      numZoomLevels: 22
    });
    map.addLayers([gterr, gmap, ghyb, gsat]);
    salina = new OpenLayers.LonLat(-97.6459, 38.7871);
    center = salina;
    map.setCenter(center.transform(geoProj, mercProj), 5);
    colors = ['ff0000', '00ff00', '0000ff', 'ffd700', 'ff00ff', '00ffff'];
    styles = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = colors.length; _i < _len; _i++) {
        color = colors[_i];
        _results.push(new OpenLayers.Style({
          'strokeWidth': 3,
          'strokeColor': '#' + color
        }));
      }
      return _results;
    })();
    kmlDir = "kml";
    kmlFilenames = ["ge.research.201205090000.N677F_flight_track.kml", "ge.research.201205111738.NA817_flight_track.kml", "ge.SMART-R.201205131825.NOXP_location.kml", "ge.SMART-R.201205111750.NOXP_location.kml", "ge.NCAR_ISS.201205111652.location.kml"];
    kmlLayers = [];
    for (i = _i = 0, _len = kmlFilenames.length; _i < _len; i = ++_i) {
      kmlFilename = kmlFilenames[i];
      kmlLayers.push(new OpenLayers.Layer.Vector('KML', {
        strategies: [new OpenLayers.Strategy.Fixed()],
        protocol: new OpenLayers.Protocol.HTTP({
          url: kmlDir + "/" + kmlFilename,
          format: new OpenLayers.Format.KML({
            extractStyles: true,
            extractAttributes: true
          })
        })
      }));
    }
    map.addLayers(kmlLayers);
    for (_j = 0, _len1 = kmlLayers.length; _j < _len1; _j++) {
      kmlLayer = kmlLayers[_j];
      kmlLayer.events.on({
        "featureselected": onFeatureSelect,
        "featureunselected": onFeatureUnselect
      });
    }
    kmlSelector = new OpenLayers.Control.SelectFeature(kmlLayers);
    map.addControl(kmlSelector);
    return kmlSelector.activate();
  };

  onFeatureSelect = function(event) {
    var content, feature, popup;
    feature = event.feature;
    console.log(feature);
    content = "<h2>" + feature.attributes.name + "</h2>" + feature.attributes.description;
    console.log(feature.attributes.description);
    popup = new OpenLayers.Popup.FramedCloud("chickenXXX", feature.geometry.getBounds().getCenterLonLat(), new OpenLayers.Size(100, 100), content, null, true);
    feature.popup = popup;
    return CATMAP.map.addPopup(popup);
  };

  onFeatureUnselect = function(event) {
    var feature;
    feature = event.feature;
    console.log(feature);
    if (feature.popup) {
      CATMAP.map.removePopup(feature.popup);
      feature.popup.destroy();
      delete feature.popup;
    }
    return map;
  };

}).call(this);
