// Generated by CoffeeScript 1.6.2
(function() {
  var CATMAP, onFeatureSelect, onFeatureUnselect;

  CATMAP = {};

  this.CATMAP = CATMAP;

  CATMAP.load_map = function(map_div_name) {
    var boulder, center, color, colors, controls, geoProj, ghyb, gmap, goesCh1Layer, goesCh4Layer, gsat, gterr, kmlDir, map, mercProj, osm, salina, styles;

    geoProj = new OpenLayers.Projection("EPSG:4326");
    mercProj = new OpenLayers.Projection("EPSG:900913");
    controls = [
      new OpenLayers.Control.MousePosition({
        displayProjection: geoProj
      }), new OpenLayers.Control.OverviewMap, new OpenLayers.Control.KeyboardDefaults, new OpenLayers.Control.LayerSwitcher, new OpenLayers.Control.Navigation
    ];
    map = new OpenLayers.Map(map_div_name, {
      controls: controls
    });
    CATMAP.map = map;
    osm = new OpenLayers.Layer.OSM();
    map.addLayer(osm);
    gterr = new OpenLayers.Layer.Google("Google Terrain", {
      type: google.maps.MapTypeId.TERRAIN
    });
    gmap = new OpenLayers.Layer.Google("Google Streets", {
      numZoomLevels: 20
    });
    ghyb = new OpenLayers.Layer.Google("Google Hybrid", {
      type: google.maps.MapTypeId.HYBRID,
      numZoomLevels: 20
    });
    gsat = new OpenLayers.Layer.Google("Google Satellite", {
      type: google.maps.MapTypeId.SATELLITE,
      numZoomLevels: 22
    });
    map.addLayers([gterr, gmap, ghyb, gsat]);
    boulder = new OpenLayers.LonLat(-105.3, 40.028);
    salina = new OpenLayers.LonLat(-97.6459, 38.7871);
    center = salina;
    map.setCenter(center.transform(geoProj, mercProj), 5);
    colors = ['ff0000', '00ff00', '0000ff', 'ffd700', 'ff00ff', '00ffff'];
    styles = (function() {
      var _i, _len, _results;

      _results = [];
      for (_i = 0, _len = colors.length; _i < _len; _i++) {
        color = colors[_i];
        _results.push(new OpenLayers.Style({
          'strokeWidth': 3,
          'strokeColor': '#' + color
        }));
      }
      return _results;
    })();
    kmlDir = "kml";
    goesCh1Layer = new OpenLayers.Layer.Image('ops.GOES-13.201305220232.4km_ch1_vis.jpg', 'img/ops.GOES-13.201305220232.4km_ch1_vis.jpg', new OpenLayers.Bounds(-105.6473, 22.9482, -65.5498, 47.9302).transform(geoProj, mercProj), new OpenLayers.Size(866, 693), {
      isBaseLayer: false,
      alwaysInRange: true
    });
    goesCh4Layer = new OpenLayers.Layer.Image('ops.GOES-13.201305220332.4km_ch4_thermal-IR.jpg', 'img/ops.GOES-13.201305220332.4km_ch4_thermal-IR.jpg', new OpenLayers.Bounds(-105.6473, 22.9482, -65.5498, 47.9302).transform(geoProj, mercProj), new OpenLayers.Size(866, 693), {
      isBaseLayer: false,
      alwaysInRange: true
    });
    map.addLayers([goesCh1Layer, goesCh4Layer]);
    goesCh1Layer.setOpacity(.5);
    goesCh4Layer.setOpacity(.5);
    return map;
  };

  onFeatureSelect = function(event) {
    var content, feature, popup;

    feature = event.feature;
    console.log(feature);
    content = "<h2>" + feature.attributes.name + "</h2>" + feature.attributes.description;
    console.log(feature.attributes.description);
    popup = new OpenLayers.Popup.FramedCloud("chickenXXX", feature.geometry.getBounds().getCenterLonLat(), new OpenLayers.Size(100, 100), content, null, true);
    feature.popup = popup;
    return CATMAP.map.addPopup(popup);
  };

  onFeatureUnselect = function(event) {
    var feature;

    feature = event.feature;
    console.log(feature);
    if (feature.popup) {
      CATMAP.map.removePopup(feature.popup);
      feature.popup.destroy();
      return delete feature.popup;
    }
  };

}).call(this);
